version: 2.1
commands:
  print_pipeline_id:
    description: "Command which prints out the pipeline id"
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  print-workflow-id:
    docker:
      - image: cimg/base:stable
    steps:
      - print_pipeline_id:
workflows:
  print-the-workflow-id:
    jobs:
      - print-workflow-id
