version: 2.1
commands:
  print_pipeline_id:
    steps:
      - run: echo ${CIRCLE_WORKFLOW_ID}
jobs:
  print-CI-id:
    docker:
      - image: cimg/base:stable
    description: "Command to print out the pipeline id"
    steps:
      - print_pipeline_id:
workflows:
  print-the-CI-id:
    jobs:
      - print-CI-id
